interface Node {
  id: ID!
}

"""
Common pagination metadata
"""
type PageInfo {
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
  startCursor: String
  endCursor: String
}

enum SortDirection {
  ASC
  DESC
}

input SortInput {
  field: String!
  direction: SortDirection!
}

type Query {
  feedback(id: ID!): Feedback
  feedbacks(first: Int, after: String, sort: SortInput): FeedbackConnection
}

type Mutation {
  createFeedback(text: String!): Feedback!
  createFeedbacks(texts: [String!]!): [Feedback!]!
}

type Feedback implements Node {
  id: ID!
  text: String!
  highlights: [Highlight!]
}

type Highlight implements Node {
  id: ID!
  quote: String!
  summary: String!
}

type FeedbackPage {
  values: [Feedback!]!
  count: Int!
}

type FeedbackConnection {
  edges: [FeedbackEdge!]!
  pageInfo: PageInfo!
}

"""
The edge contains the actual item as the "node", alongside metadata; default
is to just include the cursor metadata
"""
type FeedbackEdge {
  node: Feedback
  cursor: String!
}
